services:
  localstack:
    image: localstack/localstack:1.3.1
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=tynamo
      - AWS_SECRET_ACCESS_KEY=tynamo
      - EDGE_PORT=4566
      - DATA_DIR=${DATA_DIR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566-4587:4566-4587"
    volumes:
      - localstack-data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - tynamo

volumes:
  localstack-data:
    name: localstack-data

networks:
  tynamo:
    name: tynamo
